# Table of Content

1. **[What is Python Numpy](#python_numpy)**
2. **[Functions to Create Array](#functions)**
3. **[Attributes and Functions on Array](#operations)**
4. **[Indexing Array](#Indexing)**
5. **[Slicing Array](#Slicing)**
6. **[Operations on a 1D Array](#operations_1d)**
7. **[Operations on a 2D Array](#operations_2d)**
8. **[Arithmetic Functions in Numpy](#arithmetic_functions)**
9. **[Concatenation of Array](#concatenation)**
10. **[Stacking of Array](#stacking)**
11. **[Splitting of Array](#splitting)**
12. **[Iterating Numpy Array](#Iterating)**

<a id="python_numpy"> </a>
# 1. What is Python Numpy

The NumPy is a python package that stands for ‘Numerical Python’.<br>
                    Numpy is the core library for scientific computing, which contains a powerful n-dimensional array object, provides tools for integrating C, C++, etc.<br>
                    It contains a powerful N-dimensional array object.<br>
                  

**How to install numpy?**<br>
1. You can use-<br>
`!pip install numpy`<br>
2. You can import it as-<br>
import numpy as np

In [1]:
# import the numpy package as np
import numpy as np

## Python NumPy Array v/s List
We use python numpy array instead of a list because of the below three reasons:
1. Arrays occupy less memory<br>
2. work faster<br>
3. are convenient to use

**The N-dimensional array**<br>
An easy way to create an array from structures such as a list is to use the array() function.

In the example below, first, create two python lists. Then, create numpy arrays out of the created lists.

In [2]:
# create 2 new lists height and weight of 6 people
person_height = [5.2,  5.4, 4.4, 4.5, 5.6, 6]
person_weight = [81, 55, 65, 70, 45, 44]

# create 2 numpy arrays from height and weight from the above lists
person_height = np.array(person_height)
person_weight = np.array(person_weight)

In [3]:
# print 'person_height' array
person_height

array([5.2, 5.4, 4.4, 4.5, 5.6, 6. ])

In [4]:
# print 'person_weight' array
person_weight

array([81, 55, 65, 70, 45, 44])

**Print type of 'person_weight'**

In [5]:
# print the type of variable person_weight
print(type(person_weight))

<class 'numpy.ndarray'>


## Advantages of numpy arrays over lists

Python numpy arrays are more compact as compared to lists.

In [6]:
# consider a list of numbers
num_list = [4,5,6,1,2,3]

# add 1 to each element
num_modified_list = [i + 1 for i in num_list]

# print the list
num_modified_list

[5, 6, 7, 2, 3, 4]

In [7]:
# create an array from a list
num_array = np.array([4,5,6,1,2,3])

# add 1 to each element
num_modified_array = num_array + 1

# print the array
num_modified_array

array([5, 6, 7, 2, 3, 4])

Python numpy array are fast as compared to lists

In [8]:
# create a Numpy array using arange of size 1000000
my_array = np.arange(1000000)

# create a python list using range of size 1000000
my_list = list(range(1000000))

In [9]:
# print out execution time for the following

# time required for computations in an array
%time for _ in range(10): my_modified_array = my_array ** 2

# time required for computation in an array    
%time for _ in range(10): my_modified_list = [x ** 2 for x in my_list]

CPU times: user 14 ms, sys: 8.26 ms, total: 22.2 ms
Wall time: 20.8 ms
CPU times: user 2.37 s, sys: 132 ms, total: 2.51 s
Wall time: 2.51 s


From the above result, you can observe that the numpy arrays are faster than python lists.

Here Wall time, also called wall-clock time, measures the total time to execute a program in a computer.

<a id="functions"> </a>
# 2. Functions to Create Array

**1. An array of Zeros**<br>
The `zeros()` will create a new array of the specified size with the contents filled with zero values. 

In [1]:
import numpy as np

In [3]:
np.zeros([3,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [10]:
# to create array of zeros
# import the zeros module from library numpy
from numpy import zeros

# create a numpy ray with 3 rows and 2 columns
my_array = zeros([3,2])

# print the array
print(my_array)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


**2. An array of Ones**<br>
The `ones()` will create a new array of the specified size with its elements as unity.

In [11]:
# to create an array of ones
# import the ones module from library numpy
from numpy import ones

# create a numpy ray with 5 elements
my_array = ones([5])

# print the array
print(my_array)

[1. 1. 1. 1. 1.]


In [5]:
np.ones([3,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

**3. An array of random numbers**<br>
The `random()` function returns random numbers in the half-open interval [0.0, 1.0). The half-open interval includes 0 but excludes 1. The required number of random numbers is passed through the ‘size’ parameter.


In [12]:
# create 2D array of 3 rows and 2 columns of random numbers
my_array = np.random.random(size = (3,2))

# print the array
my_array

array([[0.57217205, 0.41309076],
       [0.76767539, 0.25948637],
       [0.26818487, 0.43001352]])

The `randn()` creates an array of the given shape with random variables from a uniform distribution between (0, 1)

In [13]:
# create 2D array of 4 rows and 2 columns of random numbers
my_array = np.random.randn(4,2)

# print the array
my_array

array([[-0.64728969, -1.2222134 ],
       [-0.64793344,  1.25576563],
       [-0.17502278,  0.08968551],
       [-0.5508807 , -1.05708355]])

The `randint()` returns random integers from low (inclusive) to high (exclusive)

In [14]:
# create an array of 3 of random numbers between 2 and 9
# the randint() will not include 10, the numbers will be generated between 2 and 9 (both inclusive)
my_array = np.random.randint(2,10,3)

# print the array
my_array

array([2, 8, 8])

**4. Create an array using `arange()`**<br>
arange() function creates an array of numbers between the given range

In [15]:
# create an array of integers between 0 to 10  
# start: start value of interval (inclusive). 0 is the default value
# stop: stop value of interval (exclusive)
# step: returns numbers with given step_size
sequence = np.arange(start = 0, stop = 10, step = 1)

# print the sequence
sequence

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [24]:
np.random.random(size=(3,2))

array([[0.80832285, 0.84507843],
       [0.315735  , 0.58460818],
       [0.12217111, 0.63633848]])

In [30]:
np.random.randn(3,2)

array([[-1.00082483, -0.05286135],
       [ 0.53436649, -1.13083569],
       [ 1.32510583,  1.92009822]])

<a id="operations"> </a>
# 3. Attributes and Functions on Array

## 3.1. Attributes: 

It is defined as a specification that defines a property of an object. Attributes of the numpy array do not have parentheses following them

**ndim:**<br>
Prints the dimension (number of axes) of the numpy array

In [16]:
quantity = np.array([(11,32,23),(34,55,46)])
print(quantity.ndim)

2


**itemsize:**<br>
Prints the memory occupied by each element.

In [17]:
quantity = np.array([(5,5,6,2,75,3)])
print(quantity.itemsize)

8


In the above example, each element occupies 4 bytes.

**dtype:**<br>
Prints the data type along with the size in bytes.

In [18]:
quantity = np.array([(1,2,3)])
print(quantity.dtype)

int64


**size:**<br>
Prints the number of elements in the array.

**shape**<br>
Prints the number of rows and columns of the array.

In [19]:
quantity = np.array([(1,2,3,4,5,6)])
print(quantity.size)
print(quantity.shape)

6
(1, 6)


## 3.2. Functions/method: 
A method is a function that belongs to an object. It takes parameters in the parentheses and returns the modified array. 

**reshape:**<br>
The reshape() is used to change the number of rows and columns of an array without changing the data.<br>

<table align="center">
    <td height = '100', width = '400'>
          <img src="reshape.png">
        </td>
</table>

In [20]:
# create an array
quantity_1 = np.array([(8,9,10),(11,12,13)])
# print the array
# \n: print on a newline
print("The original array:\n", quantity_1)

# change the shape
quantity_2 = quantity_1.reshape(3,2)
# print the array
# \n: print on a newline
print("The reshaped array:\n", quantity_2)

The original array:
 [[ 8  9 10]
 [11 12 13]]
The reshaped array:
 [[ 8  9]
 [10 11]
 [12 13]]


<a id="Indexing"> </a>
# 4. Indexing Array

**Indexing in 1 dimension**

In [21]:
# declare an array
quantity = np.array([11, 22, 33, 24, 57, 473])

# print the array
print(quantity)

[ 11  22  33  24  57 473]


Each element in the array can be accessed by passing the positional index of the element.

In [22]:
# get the 1st element
# indexing starts from '0'
print(quantity[0]) 

# get the third element
print(quantity[2]) 

11
33


**Indexing in 2 dimensions**

In [23]:
# declare a 2D array
quantity = np.array([[101, 231, 321],
              [412, 512, 622],
              [712, 821, 912]])

# print the array
quantity

array([[101, 231, 321],
       [412, 512, 622],
       [712, 821, 912]])

We can retrieve an element of the 2D array using two indices i and j - i selects the row, and j selects the column:

In [24]:
# get the element in 3rd row and 2nd column
# indexing starts from '0' 
print(quantity[2, 1])

821


In [25]:
# we can pass ith row and jth column in separate brackets ([])
# indexing starts from '0' 
print(quantity[2][1])

821


**Picking a row or column**        

We can also select a single row or column 

In [26]:
# pick the second row from the array
# indexing starts from '0' 
print(quantity[2])

[712 821 912]


In [27]:
# pick the second column from the array
# indexing starts from '0' 
print(quantity[:,2])

[321 622 912]


<a id="Slicing"> </a>
# 5. Slicing Array

**Slicing a 1D array**

In [28]:
# declare an array
price = [101, 121, 112, 123, 114]

In [29]:
# pick the second, third, and fourth element from the array 
# indexing starts from '0' 
new_price = price[1:4]  

# print the array
new_price

[121, 112, 123]

The slice notation specifies a start and end value [start:end], where 'start' is inclusive but 'end' is exclusive.

In [30]:
# first three elements
price[:3]

[101, 121, 112]

In [31]:
# all the elements from 112
price[2:]    

[112, 123, 114]

In [32]:
# get the complete array
price[:]

[101, 121, 112, 123, 114]

**Slicing a 2D array**

In [33]:
# declare a 2D array
prices = np.array([[101, 131, 122, 113, 143],
               [145, 165, 137, 318, 193],
               [240, 241, 252, 253, 324],
               [225, 126, 727, 928, 129]])

# print the array
prices

array([[101, 131, 122, 113, 143],
       [145, 165, 137, 318, 193],
       [240, 241, 252, 253, 324],
       [225, 126, 727, 928, 129]])

In [34]:
# select all rows except 1st
# select 3rd and 4th column
prices[1:,2:4]

array([[137, 318],
       [252, 253],
       [727, 928]])

**Note:** The index returns an element of the array, the slice returns a list of elements.

<a id="operations_1d"> </a>
### 6. Operations on a 1D Array

In [35]:
# declare two arrays
# first array
prices = np.array([120,230,310,410,150])

# print the array
print("The first array is",prices,"has length",len(prices))

# second array
quantity = np.arange(5)

# print the array
print("The second array is",quantity,"has length",len(quantity))

The first array is [120 230 310 410 150] has length 5
The second array is [0 1 2 3 4] has length 5


Add the two arrays

In [36]:
num_array = prices + quantity
num_array

array([120, 231, 312, 413, 154])

In [37]:
# declare another array
num_array = np.array([1,2,3,5])

# print the array
print("The new array is",num_array,"has length",len(num_array))

num_array + quantity

The new array is [1 2 3 5] has length 4


ValueError: operands could not be broadcast together with shapes (4,) (5,) 

**Remark:** If you try to add arrays with different dimensions, you get an error.              

In [38]:
# multiply each element in the array by 4 
quantity*4

array([ 0,  4,  8, 12, 16])

Use ' ** ' to compute power of the numbers.

In [39]:
# get square of each element
quantity**2

array([ 0,  1,  4,  9, 16])

**Using Numpy with Comparison Expressions**

In [40]:
price_pens = np.array([34, 45, 67, 45, 23])

# check which elements are greater than or equal to 40
# the comparison condition gives boolean output
output_array = price_pens >= 40
output_array

array([False,  True,  True,  True, False])

Pass the above boolean array to the main array to fetch the values that satisfy the comparison condition.

In [41]:
# elements greater than or equal to 40
price_pens[output_array]

array([45, 67, 45])

Rather than creating a separate array of booleans, you can specify the comparison operation directly on the main array.

In [42]:
# print my_array
price_pens

array([34, 45, 67, 45, 23])

In [43]:
# print the elements greater than or equal to 40
price_pens[price_pens >= 40]

array([45, 67, 45])

<a id="operations_2d"> </a>
### 7. Operations on a 2D Array

Let’s create 2 two-dimensional arrays, array_a and array_b.

In [37]:
def fun(n):
    return n.capitalize()
    
str = 'geeks'
fun(str)

'Geeks'

In [51]:
def ispallindrome(s):
    if s == s[::-1]:
        return 'Pallindrome'

s = 'rar'
ispallindrome(s)

'Pallindrome'

In [69]:
l = [2,4,5,9,16,25]
[x for x in l if np.sqrt(x).is_integer()]

[4, 9, 16, 25]

In [44]:
# declare two arrays
# first array
quanitity_A = np.array([[33,12],[70,61]])

# print the array
print("The first array is \n",quanitity_A)

# second array
quanitity_B  = np.array([[43,51],[72,81]])

# print the array
print("The second array is \n",quanitity_B)

The first array is 
 [[33 12]
 [70 61]]
The second array is 
 [[43 51]
 [72 81]]


Add the two array

In [45]:
# add the 2 arrays
quanitity_A + quanitity_B

array([[ 76,  63],
       [142, 142]])

Perform multiplication on array_a and array_b.

In [46]:
# multiply the 2 arrays
quanitity_A * quanitity_B

array([[1419,  612],
       [5040, 4941]])

'+=' operation on the `quanitity_A` is equivalent to adding a specified value to each element of the array. The original array gets modified using this operation.

In [47]:
# add 2 to each element
quanitity_A += 2
quanitity_A 

array([[35, 14],
       [72, 63]])

Similarly, you can use other arithmetic operations like -= and *=

In [48]:
# subtract 2 from each element 
quanitity_A -= 2

# print the array
quanitity_A 

array([[33, 12],
       [70, 61]])

In [49]:
# multiply 2 to each element 
quanitity_A *= 2

# print the array
quanitity_A 

array([[ 66,  24],
       [140, 122]])

**Matrix Multiplication**<br>

Use '@' operator to perform matrix multiplication (or matrix product).

In [50]:
quanitity_A @ quanitity_B

array([[ 4566,  5310],
       [14804, 17022]])

The same output can also be obtained by the dot().

In [51]:
quanitity_A.dot(quanitity_B)

array([[ 4566,  5310],
       [14804, 17022]])

<a id="arithmetic_functions"> </a>
### 8. Arithmetic Functions in Numpy

In [52]:
# given array
performance_scores = np.array([5,7,8,2,4])

# print the array
performance_scores

array([5, 7, 8, 2, 4])

**sum():**<br>
The sum() function adds all the values in the array and gives a scalar output.

In [53]:
# add all the elements of 'performance_scores'
performance_scores.sum()

26

**min():**<br>
The min function finds the lowest value in the array.

In [54]:
# find minimum of 'performance_scores'
performance_scores.min()

2

**power():**<br>
The power function raises the numbers in the array to the given value.

In [55]:
# get cube of elements of 'performance_scores'
np.power(performance_scores,3)

array([125, 343, 512,   8,  64])

**Using the axis parameter**<br>
Use the axis parameter with value 0, to find the sum of all the values in a single column.

In [56]:
# create a 2D array of random integers
num_array = np.random.randint(1,10,(2,3))
num_array

array([[3, 8, 6],
       [9, 7, 1]])

In [57]:
# obtain the sum over columns
num_array.sum(axis=0)

array([12, 15,  7])

Similarly, to find the lowest value across a particular row, use the axis parameter with a value ‘1'.

In [58]:
# obtain the sum over rows
num_array.min(axis=1)

array([3, 1])

<a id="concatenation"> </a>
### 9. Concatenation of Array

The arrays can be concatenated only if they have the same shape, except in the dimension corresponding to the axis of concatenation.

**Concatenate 1D array**

In [59]:
# concatenate two 1D arrays
# production on day 1 
production_day_1 = np.array([11, 22, 13])

# production on day 2
production_day_2 = np.array([23, 22, 12])

# concatenate the two array giving the production for 2 days
np.concatenate([production_day_1, production_day_2])

array([11, 22, 13, 23, 22, 12])

You can also concatenate more than two arrays at once.

In [60]:
# production on day 3
production_day_3 = np.array([23,45])

# concatenate the two array giving the production for 3 days
total_produce = np.concatenate([production_day_1, production_day_2, production_day_3])

# print total_produce
total_produce

array([11, 22, 13, 23, 22, 12, 23, 45])

**Concatenate 2D array**

In [61]:
# create a 2D array
scores_player_1 = np.array([[1, 2, 3],
                 [4, 5, 6]])
scores_player_1

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
# create a 2D array
scores_player_2 = np.array([[5, 6, 3],
                 [4, 9, 6]])
scores_player_2

array([[5, 6, 3],
       [4, 9, 6]])

**concatenate along the first axis**

In [63]:
# by default concatenate() is along 'axis = 0'
np.concatenate([scores_player_1, scores_player_2])

array([[1, 2, 3],
       [4, 5, 6],
       [5, 6, 3],
       [4, 9, 6]])

**concatenate along the second axis**

In [64]:
np.concatenate([scores_player_1, scores_player_1], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

**Concatenate 1D and 2D array**

In [8]:
# concatenate the 1D and 2D arrays
# consider a 1D array -- 'num_array_1D'
num_array_1D = np.array([[23,45,55],[22,33,44]])

# consider a 2D array -- 'num_array_2D'
num_array_2D = np.array([[5, 6, 3],
                 [4, 9, 6]])

np.concatenate((num_array_1D, num_array_2D), axis = 0)

array([[23, 45, 55],
       [22, 33, 44],
       [ 5,  6,  3],
       [ 4,  9,  6]])

**Note:** One can not concatenate the arrays with different dimensions

<a id="stacking"> </a>
### 10. Stacking of Array

Stacking can be used to join 2 or more arrays along the different axes. This method can also be used to create higher-dimensional arrays using lower-dimensional arrays. 
Numpy vstack, Numpy hstack, and Numpy concatenate are all similar functions to join the arrays.

In [66]:
# create two arrays
num_array_1 = np.array([[1, 2, 3], [4, 5, 6]])
num_array_2 = np.array([[7, 8, 9], [10, 11, 12]])
print(num_array_1) 
print(num_array_2)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


**NumPy stack** enables you to combine arrays along the specified axis. We can create a higher-dimensional array using stack().

In [67]:
# stack arrays along the 1st axis
array_stack = np.stack((num_array_1, num_array_2), axis=1)
array_stack

array([[[ 1,  2,  3],
        [ 7,  8,  9]],

       [[ 4,  5,  6],
        [10, 11, 12]]])

**NumPy hstack** enables you to combine arrays horizontally.

In [68]:
# stack arrays in sequence horizontally (column wise)
array_hstack = np.hstack((num_array_1, num_array_1))
array_hstack

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

**Numpy vstack** enables you to combine arrays vertically.

<table align="center">
    <td width = '250'>
            <img src="Vstack.png">
        </td>
</table>

In [69]:
# stack arrays in sequence vertically (row wise)
array_vstack = np.vstack([num_array_1, num_array_2])
array_vstack

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

**Numpy dstack** will stack arrays along the third axis. It converts each array as the column of the modified array.

In [70]:
# stack arrays in sequence depth wise (along the third axis)
array_dstack = np.dstack((num_array_1, num_array_1))
array_dstack

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5],
        [6, 6]]])

**Numpy column_stack** enables you to stack 1D array as 2D array.

In [71]:
# create two 1D array
num_array_1 = np.array([1,4,8])
num_array_2 = np.array([2,5,7])

# stack arrays as 2D array
array_vstack = np.column_stack([num_array_1, num_array_2])
array_vstack

array([[1, 2],
       [4, 5],
       [8, 7]])

In [72]:
# check the dimension of stacked array
np.ndim(array_vstack)

2

**block()** is used to assemble array from a nested list of blocks

In [73]:
# create a block matrix using 1D array

m1 = np.array([4])
m2 = np.array([7])
m3 = np.array([6])
m4 = np.array([3])

# 2D matrix using block()
np.block([[m1, m2],
        [m3,m4]])

array([[4, 7],
       [6, 3]])

<a id="splitting"> </a>
### 11. Splitting of Array

Splitting is used to split the array into multiple sub-arrays. It is the opposite of concatenation, which is implemented by functions like split(), hsplit(), and so on.

<table align="center">
    <td width = '300'>
            <img src="Split.png">
</table>

**split():**

In [74]:
# declare an array
array_x = np.arange(8) 

# split the array into sub-arrays
np.split(array_x, 2)

[array([0, 1, 2, 3]), array([4, 5, 6, 7])]

**Split the 1D array at positions indicated**

In [75]:
# the split occurs at 5th and 7th indices
array_y = np.split(array_x,[5,7])

# print array
print(array_y)

[array([0, 1, 2, 3, 4]), array([5, 6]), array([7])]


In [76]:
# split 'array_x' into 3 sub-arrays
np.split(array_x, 3)

ValueError: array split does not result in an equal division

**Remark:** The split() function does not allow the integer (N) as the number of splits if N does not divide the array into sub-arrays of equal length 
                    

**array_split():** It is used to split the array into sub-arrays. It takes the integer 'N' as the input for the number of splits, even if 'N' does not divide the array into sub-arrays of equal length.<br>

In [77]:
# split 'array_x' into 3 sub-arrays using 'array_split'
np.array_split(array_x, 3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7])]

We split the array of length 8 into 3 sub-arrays; the function 'array_split()' returns <i>8 % 3 (=2)</i> sub-arrays of size <i>8//3 + 1 (=3)</i> and the rest (i.e. one sub-array) of size <i>8//3 (=2)</i>.

**vsplit():**<br>
The vsplit() function is used to split an array into multiple sub-arrays vertically (row-wise).

<table align="center">
        <td height="100", width = '600'>
            <img src="Vsplit.png">
        </td>
</table>

In [78]:
# declare an array
my_array = np.arange(20.0)
print("The array is:\n",my_array)

# reshape the array in 4 rows and 5 columns
my_reshaped_array = my_array.reshape(4,5)

# print the array
print("The reshaped array is:\n",my_reshaped_array)

The array is:
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19.]
The reshaped array is:
 [[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]]


In [79]:
# split the array vertically
np.vsplit(my_reshaped_array , 2)

[array([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]]), array([[10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]])]

**hsplit():**<br>
The hsplit() function is used to split an array into multiple sub-arrays horizontally (column-wise).

<table align="center">
    <td width = '200'>
            <img src="Hsplit.png">
        </td>
</table>

In [80]:
# declare an array
my_array = np.arange(16.0).reshape(4,4)

# print an array
my_array

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [81]:
# split the array horizontally
np.hsplit(my_array, 2)

[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]), array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]

**dsplit():**<br>
The dsplit() function is used to split an array into multiple sub-arrays.

In [82]:
# declare an array
my_array = np.arange(12.0).reshape (2,2,3)

# print it
my_array

array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]],

       [[ 6.,  7.,  8.],
        [ 9., 10., 11.]]])

In [83]:
# split the array along the depth in 3 subgroups
np.dsplit(my_array,3)

[array([[[0.],
         [3.]],
 
        [[6.],
         [9.]]]), array([[[ 1.],
         [ 4.]],
 
        [[ 7.],
         [10.]]]), array([[[ 2.],
         [ 5.]],
 
        [[ 8.],
         [11.]]])]

<a id="Iterating"> </a>
### 12. Iterating Numpy Array

**Iterating a One-dimensional Array**<br>
Iterating a one-dimensional array with the use of 'for loop'.

In [84]:
# create 1D array
num_array = np.arange(12)

# add 10 to each element 
# use a for loop to add 10 to each element
for i in num_array:
    print(i+10)

10
11
12
13
14
15
16
17
18
19
20
21


**Iterating a Two-dimensional Array**<br>
If we use the same syntax to iterate a two-dimensional array, we will only be able to iterate a row.

In [10]:
my_array = np.arange(12)
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [15]:
my_array.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [85]:
# create a 2D array
my_array = np.arange(12).reshape(4,3)
# print the array
# \n : print on newline
print("The declared array is:\n",my_array)


# add 11 to each element
print("\n The modified array is:\n")
# use a for loop to add 11 to each element
for i in my_array:
    print(i+11)

The declared array is:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

 The modified array is:

[11 12 13]
[14 15 16]
[17 18 19]
[20 21 22]


**To iterate each element in the two-dimensional array, use the nested for loop.**

In [86]:
# use a for loop to add 11 to each element
for i in my_array:              # for every row
    for j in i:                 # for an element in a row
        print(j+11)             # add 11 to it and print it

11
12
13
14
15
16
17
18
19
20
21
22


**nditer() object**<br>
NumPy provides a multi-dimensional iterator object called nditer() to iterate the elements of an array.

In [87]:
# multiply each element in the 2D array by 5
# nditer(): efficiently iterating through arrays over multidimensional object 
for i in np.nditer(my_array):
    print(i*5)

0
5
10
15
20
25
30
35
40
45
50
55
